name: iOS Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cd xcodeproj folder
        run: |
            cd ios
            ls
      - name: Test
        run: |
           xcodebuild  test -project F2.xcodeproj -scheme F2Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5' 
